src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
class Customer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::GUID, unique: true)]
    private ?string $code = null;

    #[ORM\OneToMany(mappedBy: 'customer', targetEntity: Project::class, orphanRemoval: true)]
    private Collection $projects;

    public function __construct()
    {
        $this->projects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * @return Project[]
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): self
    {
        if (!$this->projects->contains($project)) {
            $this->projects->add($project);
            $project->setCustomer($this);
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        if ($this->projects->removeElement($project)) {
            // set the owning side to null (unless already changed)
            if ($project->getCustomer() === $this) {
                $project->setCustomer(null);
            }
        }

        return $this;
    }
}

src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateStart = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateEnd = null;

    #[ORM\Column]
    private ?int $hours = null;

    #[ORM\Column]
    private ?int $costPerHour = null;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'projects')]
    private Collection $categories;

    #[ORM\ManyToOne(inversedBy: 'projects')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Customer $customer = null;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->dateStart;
    }

    public function setDateStart(\DateTimeInterface $dateStart): self
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->dateEnd;
    }

    public function setDateEnd(?\DateTimeInterface $dateEnd): self
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }

    public function getHours(): ?int
    {
        return $this->hours;
    }

    public function setHours(int $hours): self
    {
        $this->hours = $hours;

        return $this;
    }

    public function getCostPerHour(): ?int
    {
        return $this->costPerHour;
    }

    public function setCostPerHour(int $costPerHour): self
    {
        $this->costPerHour = $costPerHour;

        return $this;
    }

    /**
     * @return Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    public function getPrice(): int
    {
        return $this->getHours() * $this->getCostPerHour();
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use App\Entity\Customer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CustomerController extends AbstractController
{
    #[Route('/customer/{code}', name: 'customer_show', methods: ['GET'])]
    public function index(Customer $customer): Response
    {
        return $this->render('customer/show.html.twig', [
            'customer' => $customer,
        ]);
    }
}

templates/customer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ customer.name }}{% endblock %}

{% block body %}

    <section class="container">

        <h1>Welcome on your dashboard {{ customer.name }}</h1>

        <p>Here you can see a list of all your current projects with us!</p>

        <h2>Projects list</h2>

        <hr>

        <div class="projects-list">
            {% for project in customer.projects %}
                <article class="card mb-2">
                    <div class="card-body">
                        <div class="d-flex align-items-center gap-2">
                            <h3 class="card-title">
                                {{ project.name }}
                            </h3>
                            <em class="text-secondary">
                                ({{ project.dateStart|date('d/m/Y') }})
                            </em>
                        </div>
                        <ul>
                            <li>
                                <i class="far fa-clock"></i>
                                <strong>Hours</strong> : {{ project.hours }}
                            </li>
                            <li>
                                <i class="fas fa-money-bill-1"></i>
                                <strong>Cost per hour</strong> : {{ project.costPerHour }} €
                            </li>
                            <li>
                                <i class="fas fa-money-bills"></i>
                                <strong>Total cost</strong> : {{ project.price }} €
                            </li>
                        </ul>
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: 15%"></div>
                        </div>
                    </div>
                </article>
            {% endfor %}
        </div>

    </section>

{% endblock %}